#!/usr/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'exabgp===4.0.0-0478a014','console_scripts','exabgp'
__requires__ = 'exabgp===4.0.0-0478a014'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('exabgp===4.0.0-0478a014', 'console_scripts', 'exabgp')()
    )
